name: Run Telegram Bot

on:
  push:
  #  branches:
  #    - main  # Запуск при обновлении кода в main
  #schedule:
  #  - cron: '* * * * *'  # Запуск каждый час
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  run-bot:
    runs-on: windows-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          choco install googlechrome chromedriver -y

      - name: Запуск бота
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -u script.py
