name: Run Telegram Bot

on:
  push:
  #  branches:
  #    - main  # Запуск при обновлении кода в main
  # schedule:
  #  - cron: '0 * * * *'  # Запуск каждый час
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Установка Firefox и GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/geckodriver
          sudo chmod +x /usr/local/bin/geckodriver
          firefox --version
          geckodriver --version

      - name: Запуск бота
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -u script.py